name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          yarn install

      - name: Build the application
        run: |
          yarn build

      - name: Extract build files 
        run: |
          mkdir -p ./build
          cp -r ./dist/* ./build/

      - name: Modify build directory permissions
        run: |
          sudo chown -R www-data:www-data build
          sudo chmod -R 755 build
