name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build the application
        run: |
          docker build -t copyyt-app .

      - name: Extract build files
        run: |
          docker create --name copyyt-temp copyyt-app
          docker cp copyyt-temp:/app ./build
          docker rm copyyt-temp

